[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "libmad"
version = "0.0.0"
description = "Python bindings for libMad"
requires-python = ">=3.9"
dependencies = ["platformdirs>=4"]

[tool.setuptools.packages.find]
where = ["."]
include = ["libmad*"]
